### ISSUE TITLE
conda recipe for pysolid

### ISSUE THREAD

**Issue by yunjunz** [insarlab/PySolid#12]
Open an issue here to keep track of things for pysolid, so that https://github.com/insarlab/MintPy/issues/648 could be focused on mintpy itself.

@pbrotoisworo are you able to use pysolid on Windows? If so, how do you install it, especially how do you compile the Fortran code?

**Comment by pbrotoisworo** [comment]
@yunjunz I had no idea PySolid was not supported on Windows and I've been able to run analyses all this time and there were no errors regarding PySolid. But I think it's because it doesn't run the SET analysis. I assume it only runs correct_SET in certain situations only? I just checked my logs and here is the relevant section:

```
******************** step - correct_SET ********************
Input data seems to be geocoded. Lookup file not needed.
No solid Earth tides correction.
```

PySolid 0.1.2 is installed and shows up when I type `conda list` or `pip list`. Here is an image of the pysolid folder in site-packages:
![image](https://user-images.githubusercontent.com/32087633/132174577-ac6f7f58-e65f-4f80-bfff-33d60d300c07.png)

I assume that's the uncompiled Fortran code?

If you are curious. Here is the YML file I used to prepare my MintPy environment in a Windows environment. As of writing, I am able to just type the `conda env create` command and then I can already start doing MintPy analyses.

```YML
# conda env create -f <FILE>.yml
name: mintpy
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python>=3.6,<3.9
  - git
  - cartopy
  - cvxopt
  - dask>=1.0
  - dask-jobqueue>=0.3
  - defusedxml
  - fiona
  - h5py<3
  - hyp3_sdk
  - lxml
  - matplotlib
  - numpy
  - pip
  - pyproj
  - scikit-image
  - scipy
  - pip:
    - git+https://github.com/insarlab/PySolid.git
    - git+https://github.com/tylere/pykml.git
    - git+https://github.com/yunjunz/PyAPS.git
    - git+https://github.com/insarlab/MintPy.git
    - git+https://github.com/ASFHyP3/hyp3-lib.git
    - sentinelsat
    - PyQt5
    - PyQt5Designer
    - pytest
  # pyaps dependencies
  - cdsapi
  - ecCodes
  - netcdf4
  - pygrib
  - pyhdf
  # pyresample dependencies
  - pyresample
  - openmp
  - pykdtree
  - xarray
  - zarr


```
